language:node_js
node_js:
      - "6.10.0"
install:
      - npm install -g firebase-tools
      - npm install
script:
      - npm run build
after_success:
      - firebase deploy --token $FIREBASE_TOKEN
      - echo 'Deployed.!'